export let PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export let PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export let PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export let FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
export let SET_INGREDIENTS = 'SET_INGREDIENTS';
export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS';